import { useMemo } from "react";
import { ScoreSummary } from "./ScoreSummary";
import { FeedbackItemCard } from "./FeedbackItemCard";
import type { DesignFeedback, FeedbackItem, Severity } from "../types";

type Props = {
  feedback: DesignFeedback;
  cacheHit: boolean;
  selectedItem: FeedbackItem | null;
  onSelectItem: (item: FeedbackItem | null) => void;
};

const SEVERITY_ORDER: Severity[] = ["critical", "important", "suggestion"];
const SEVERITY_LABEL: Record<Severity, string> = {
  critical: "Critical",
  important: "Important",
  suggestion: "Suggestions",
};

export function FeedbackPanel({ feedback, cacheHit, selectedItem, onSelectItem }: Props) {
  const grouped = useMemo(() => {
    const groups: Record<Severity, FeedbackItem[]> = {
      critical: [],
      important: [],
      suggestion: [],
    };
    feedback.gaps.forEach((item) => groups[item.severity].push(item));
    return groups;
  }, [feedback]);

  return (
    <aside
      className="flex h-full w-96 flex-shrink-0 flex-col overflow-hidden border-l border-slate-200 bg-slate-50"
      aria-label="Design feedback"
    >
      <ScoreSummary feedback={feedback} cacheHit={cacheHit} />

      <div className="flex-1 overflow-y-auto p-3">
        {SEVERITY_ORDER.map((severity) => {
          const items = grouped[severity];
          if (items.length === 0) return null;
          return (
            <section key={severity} className="mb-4">
              <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">
                {SEVERITY_LABEL[severity]} ({items.length})
              </h3>
              <div className="space-y-2">
                {items.map((item, i) => (
                  <FeedbackItemCard
                    key={`${severity}-${i}`}
                    item={item}
                    isSelected={selectedItem === item}
                    onSelect={() =>
                      onSelectItem(selectedItem === item ? null : item)
                    }
                  />
                ))}
              </div>
            </section>
          );
        })}

        {feedback.missingComponents.length > 0 && (
          <section className="mb-4">
            <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">
              Missing components
            </h3>
            <ul className="space-y-1.5 rounded-md border border-slate-200 bg-white p-3">
              {feedback.missingComponents.map((c, i) => (
                <li key={i} className="flex gap-2 text-xs text-slate-700">
                  <span className="text-slate-400">•</span>
                  <span>{c}</span>
                </li>
              ))}
            </ul>
          </section>
        )}

        {feedback.tradeoffQuestions.length > 0 && (
          <section className="mb-4">
            <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">
              Trade-off questions to think about
            </h3>
            <ul className="space-y-1.5 rounded-md border border-slate-200 bg-white p-3">
              {feedback.tradeoffQuestions.map((q, i) => (
                <li key={i} className="flex gap-2 text-xs text-slate-700">
                  <span className="text-slate-400">?</span>
                  <span className="leading-relaxed">{q}</span>
                </li>
              ))}
            </ul>
          </section>
        )}

        <p className="mt-4 text-[10px] text-slate-400">
          Generated by {feedback.llmModel} · {feedback.llmTokensUsed.toLocaleString()} tokens
        </p>
      </div>
    </aside>
  );
}
